### ISSUE TITLE
[BE] 의사 임무 수행 기능

### ISSUE THREAD

**Issue by 0Chord** [boostcampwm-2024/web12-MafiaCamp#104]
## ❓ 어떤 기능인가요?

- 마피아 게임 중 의사인 유저가 임무를 수행하는 기능

## 📝 기능 설명

- 의사인 유저는 마피아 게임 중 살리고 싶은 유저를 살릴 수 있어야 한다.

## ✅ TODO

구현해야 하는 기능에 대해 체크리스트를 작성해 주세요.

- [ ] 의사가 없을 경우 스킵해야한다
- [ ] 본인 포함 특정 인원을 선택을 할 수 있도록 한다. 
- [ ] 앞서 마피아가 고른 희생자와 비교를 하여 살릴지 죽일지 결정해야한다.
