### ISSUE TITLE
[BE] 각 직업 임무 수행 기능 테스트

### ISSUE THREAD

**Issue by simjaesung** [boostcampwm-2024/web12-MafiaCamp#171]
## ❓ 어떤 기능인가요?

- 경찰, 마피아, 의사의 임무 수행 테스트 작업입니다.

## 📝 기능 설명

- 경찰, 마피아, 의사들이 의도한대로 임무를 수행하고 그에 대한 결과가 나타나는지에 대한 테스트코드를 작성하는 작업입니다.

## ✅ TODO

- [ ] 경찰 임무 수행 테스트
- [ ] 마피아 임무 수행 테스트
- [ ] 의사 임무 수행 테스트

## 📚 참고할만한 자료(선택)

- 추가적으로 참고할 만한 사항이 있으면 적어주세요.
- 없는 경우 해당 단락을 삭제해 주세요.
