### ISSUE TITLE
[FE] 메인 페이지 UI 구현

### ISSUE THREAD

**Issue by HyunJinNo** [boostcampwm-2024/web12-MafiaCamp#43]
## ❓ 어떤 기능인가요?

- MafiaCamp 웹 사이트의 메인 페이지 UI를 구현합니다.

## 📝 기능 설명

- MafiaCamp 웹 사이트의 메인 페이지 UI를 Lottie Animation과 framer-motion 라이브러리 등을 활용하여 구현합니다.

## ✅ TODO

구현해야 하는 기능에 대해 체크리스트를 작성해 주세요.

- [ ] lottie-react 라이브러리 설치
- [ ] framer-motion 라이브러리 설치
- [ ] 메인 페이지 UI 구현
