### ISSUE TITLE
[BE] 실시간 투표 기능

### ISSUE THREAD

**Issue by 0Chord** [boostcampwm-2024/web12-MafiaCamp#99]
## ❓ 어떤 기능인가요?

- 각 방마다 마피아를 선택하는 투표 기능입니다.

## 📝 기능 설명

- 마피아 선택 및 최후 변론 투표 기능을 만들었습니다.

## ✅ TODO

구현해야 하는 기능에 대해 체크리스트를 작성해 주세요.
- [ ]  각 방마다 투표함을 구분한다.
- [ ]  유저가 마피아라고 생각하는 사람을 지목하는데 지목을 한 명 밖에 못하도록 제한한다.
- [ ]  15초동안 투표를 집계하여 최종적으로 클라이언트에게 보낸다.
- [ ]  15초 뒤 집계할 때 투표를 안한 유저는 본인 자동으로 지목하도록 지정한다.
- [ ]  최종 투표 시 공동 지목이 된다면 유저끼리의 투표함을, 한사람이 지목된다면 그 사람에 대한 투표함을 만든다.

## 📚 참고할만한 자료(선택)

- 추가적으로 참고할 만한 사항이 있으면 적어주세요.
- 없는 경우 해당 단락을 삭제해 주세요.
